# Use the README file as a reference to customize settings.

User:
  fields:
    default: uuid, name, email, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: name, email, password, password_confirmation, admin
  relationships:
  application: Application
